apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-app
  name: node-service
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: node-app